In [1]:
import numpy as np

In [5]:
# Numpy Indexing And Slicing of Vectors
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
arr[6]

17

In [25]:
arr[1:5]

array([12, 13, 14, 15])

In [27]:
arr[:5]

array([11, 12, 13, 14, 15])

In [29]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [31]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [33]:
arr[3::2]

array([14, 16, 18, 20])

In [35]:
arr[4]

15

In [37]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [45]:
# Numpy Indexing and Slicing of Matrix
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [47]:
arr[0]

array([1, 2, 3, 4, 5])

In [49]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [51]:
arr[5]

array([26, 27, 28, 29, 30])

In [57]:
arr[0,0]

1

In [59]:
arr[0,4]

5

In [61]:
arr[5,4]

30

In [67]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [75]:
slice_arr = arr[3:,3:]
slice_arr

array([[19, 20],
       [24, 25],
       [29, 30]])

In [77]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [97]:
# Boolean Indexing
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [91]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [99]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])