In [1]:
# Array Operations
import numpy as np

In [3]:
# Arithmetic operations
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1

array([1, 2, 3, 4, 5])

In [5]:
a2

array([ 6,  7,  8,  9, 10])

In [7]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [9]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [11]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [13]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [21]:
a1 // a2

array([0, 0, 0, 0, 0])

In [23]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [39]:
# Broadcasting
l = [10,20,30,40]
arr = np.array(l)
arr + 10

array([20, 30, 40, 50])

In [41]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [46]:
arr2 = arr2 + 10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [54]:
# Deep and Shallow copy
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [56]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [58]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [62]:
a[4:6] * 10

array([50, 60])

In [66]:
a
b = a

In [74]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [79]:
a
b = a.copy()

In [81]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [83]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [89]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A

array([[1, 2],
       [3, 4]])

In [91]:
B

array([[5, 6],
       [7, 8]])

In [93]:
A * B

array([[ 5, 12],
       [21, 32]])

In [95]:
A @ B

array([[19, 22],
       [43, 50]])

In [99]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [101]:
A

array([[1, 2],
       [3, 4]])

In [103]:
A.T

array([[1, 3],
       [2, 4]])

In [113]:
# Advance Array Manipulation
# Stacking Array
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [115]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [119]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [129]:
# Splitting array
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [135]:
np.split(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [139]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [141]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [149]:
a = np.hsplit(c,4)
for i in a:
    print(i)

[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1]
 [ 5]
 [ 9]
 [13]]
[[ 2]
 [ 6]
 [10]
 [14]]
[[ 3]
 [ 7]
 [11]
 [15]]
