In [11]:
import numpy as np

In [29]:
# Basic Array creation
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [56]:
# List
a = [1,2,3,4,"hello"]
b = [1,2,3.5]
print(a)
print(b)

[1, 2, 3, 4, 'hello']
[1, 2, 3.5]


In [66]:
np.array(a) # String Array

array(['1', '2', '3', '4', 'hello'], dtype='<U21')

In [68]:
np.array(b) # Float Array

array([1. , 2. , 3.5])

In [72]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [74]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
# Array generation function
# Vector array []
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [112]:
# Matrix Array [[]]
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [92]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [102]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [116]:
# Random Generation function
np.random.rand(10)

array([0.88599607, 0.0450865 , 0.15015115, 0.62088118, 0.42028283,
       0.91601076, 0.66214224, 0.12783641, 0.47072049, 0.13432402])

In [118]:
# 0 to 1 Normalization
# 3 to -3 Standardization
np.random.randn(10)

array([-0.10613613,  0.96333182, -0.41582743,  0.32844249, -0.88810911,
        1.19442142, -0.36774904, -0.57292448, -1.90126353,  1.03764233])

In [129]:
np.random.randint(6)

5

In [131]:
np.random.randint(10,20,10)

array([18, 14, 15, 10, 15, 16, 11, 11, 15, 10])

In [135]:
# Array Attributes
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [161]:
arr.shape

(3, 3)

In [151]:
arr.size

9

In [153]:
arr.dtype

dtype('int64')

In [157]:
# Array Methods
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [159]:
arr.min()

1

In [163]:
arr.max()

9

In [165]:
arr.sum()

45

In [189]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [181]:
arr.mean()

5.0

In [183]:
arr.std()

2.581988897471611

In [185]:
arr.argmax()

8

In [187]:
arr.argmin()

0

In [191]:
# Reshaping and resizing
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [195]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [197]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [201]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])